//! Record layer defragmentation
//!

use thiserror::Error;

use crate::{
    codec::Codec,
    error::{Error, InvalidMessage},
    msgs::ProtocolVersion,
    reader::Reader,
    record_layer::{
        CIPHERTEXT_FRAGMENT_MAX_LEN, ContentType, ContentTypeName, PLAINTEXT_FRAGMENT_MAX_LEN,
        RECORD_HEADER_LEN,
        record::{EncodedPayload, Record},
    },
};

/// Reconstructs [`Record<EncodedPayload>`] from an input buffer
pub struct Deframer<'a> {
    /// Data read from the socket, waiting to be parsed into messages
    input_buffer: &'a mut Vec<u8>,
}

impl<'a> Deframer<'a> {
    pub fn new(buf: &'a mut Vec<u8>) -> Self {
        Self { input_buffer: buf }
    }
}

impl<'a> Iterator for Deframer<'a> {
    type Item = Result<Record<EncodedPayload>, Error>;

    fn next(&mut self) -> Option<Self::Item> {
        let mut reader = Reader::new(&self.input_buffer);

        // First, try to read a record header from the buffer
        let header_res = parse_record_header(&mut reader);

        let (content_type, version, length) = match header_res {
            Ok(r) => r,
            Err(err) => {
                let err = match err {
                    // If we can't read a full header, we just can't return a message for now
                    ParsingError::TooShortForHeader | ParsingError::TooShortForPayload => {
                        return None;
                    }

                    // If another error occurs, the header is invalid and we should terminate
                    // the connection
                    ParsingError::InvalidContentType => InvalidMessage::InvalidContentType,
                    ParsingError::InvalidProtocolVersion => InvalidMessage::UnknownProtocolVersion,
                    ParsingError::RecordTooLong => InvalidMessage::RecordOverflow,
                };
                return Some(Err(err.into()));
            }
        };

        let fragment_end = RECORD_HEADER_LEN + length as usize;

        // Try to get the full fragment
        self.input_buffer.get(RECORD_HEADER_LEN..fragment_end)?;

        // Get the fragment and shift the buffer to the left
        let fragment = self
            .input_buffer
            .drain(0..fragment_end) // Remove the whole record from the buffer
            .skip(RECORD_HEADER_LEN); // Skip the header

        let record = Record {
            typ: content_type,
            version,
            payload: EncodedPayload(Vec::from_iter(fragment)),
        };

        Some(Ok(record))
    }
}

/// Parse a record header
fn parse_record_header(
    buf: &mut Reader,
) -> Result<(ContentType, ProtocolVersion, u16), ParsingError> {
    let content_type = ContentType::decode(buf).map_err(|_| ParsingError::TooShortForHeader)?;

    if ContentTypeName::try_from(content_type).is_err() {
        return Err(ParsingError::InvalidContentType);
    };

    let version = ProtocolVersion::decode(buf).map_err(|_| ParsingError::TooShortForHeader)?;

    // "MUST be set to 0x0303 for all records generated by
    //  a TLS 1.3 implementation other than an initial ClientHello"
    //
    // Since we're the client and force TLS 1.3, we should only receive 0x0303 (TLSv1_2)
    if version != ProtocolVersion::TLSv1_2 {
        return Err(ParsingError::InvalidProtocolVersion);
    }

    let length = u16::decode(buf).map_err(|_| ParsingError::TooShortForHeader)?;

    // The length limit is different for appli
    if content_type == ContentType::ApplicationData {
        if length > CIPHERTEXT_FRAGMENT_MAX_LEN {
            return Err(ParsingError::RecordTooLong);
        }
    } else {
        if length > PLAINTEXT_FRAGMENT_MAX_LEN {
            return Err(ParsingError::RecordTooLong);
        }
    }

    // "The length MUST NOT exceed 2^14 bytes"
    if length > CIPHERTEXT_FRAGMENT_MAX_LEN {}

    Ok((content_type, version, length))
}

/// Errors that can happen while parsing a record from a buffer
#[derive(Debug, Error)]
enum ParsingError {
    /// When we can't read enough bytes for the header
    #[error("buffer too short for header")]
    TooShortForHeader,

    /// When we can't read enough bytes for the header
    #[error("buffer too short for payload")]
    TooShortForPayload,

    /// When the content type is invalid
    #[error("invalid content type")]
    InvalidContentType,

    /// When the protocol version is invalid
    #[error("invalid protocol version")]
    InvalidProtocolVersion,

    /// When the record exceeds the maximum length
    #[error("record too long")]
    RecordTooLong,
}
