import {
    Button,
    VerticalBox,
    LineEdit,
    ScrollView,
    HorizontalBox,
} from "std-widgets.slint";
import { MainLayout } from "layout/Main.slint";
import { Theme } from "theme.slint";

// Export models for Rust access
export { Chat } from "models/Chat.slint";
export { MessageData } from "models/Message.slint";
export { Conversation } from "models/Conversation.slint";

export component AppWindow inherits Window {

    title: "Rust Messenger";
    min-width: 800px;
    min-height: 600px;

    background: Theme.background;

    in-out property <string> username: "";
    in-out property <bool> checked: false;

    callback check-user(string);

    VerticalBox {
        spacing: 15px;
        padding: 30px;

        Text {
            text: "Vérification du compte";
            font-size: 20px;
        }

        input := LineEdit {
            placeholder-text: "Entrez votre e-mail";
        }

        Button {
            text: "Vérifier";
            primary: true;
            clicked => { root.check-user(input.text) }
        }

        // Zone d'affichage dynamique
        if (root.checked) : Text {
            // Si username n'est pas vide, il existe
            text: root.username != "" 
                ? "Utilisateur trouvé : " + root.username 
                : "Aucun compte trouvé. Voulez-vous vous inscrire ?";
            color: root.username != "" ? green : orange;
        }
    }

    MainLayout { }
}
